name: ChestShop-towny

main: com.acrobot.chestshop.towny.Towny
version: '${project.bukkitPluginVersion}'
api-version: ${project.bukkitAPIVersion}
folia-supported: true

author: Acrobot
description: A towny integration for ChestShop 
 
depend: [ChestShop, Towny]

permissions:
  ChestShop.towny.bypass:
    default: op
  ChestShop.towny.townshop:
    default: op
  ChestShop.towny.nationshop:
    default: op